fieldLayouts:
  edcf9468-44d0-488a-b1f7-190d57caa4fb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 118eb80e-0302-4270-8e15-63959c7269b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45e79cc6-1d09-4988-a7b2-55288a562200
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44eef1aa-da90-4a5c-9fe4-213c43e7f967
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dc462170-e965-4604-a32b-68117eb8bd07
        userCondition: null
fs: uploadsFs
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
