defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  2b7f435b-0d31-47db-bae2-66d447e8199f: # DecoWorld
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
